[build]
  functions = "netlify/functions"
  publish = "."
  command = "npm install"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["stripe"]

[build.processing]
  skip_processing = true

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
